### ISSUE TITLE
Support Secret Engine v2

### ISSUE THREAD

**Issue by JulianNeuhaus27** [fishi0x01/vsh#105]
It looks like the [secret engine version2](https://www.vaultproject.io/docs/secrets/kv/kv-v2) is not supported.
`ls` is returning empty Vault from root path.
```
https://vault.xxx.de /> ls

https://vault.xxx.de />
```
Even though the Vault is definitely not empty 🙂

**Comment by fishi0x01** [comment]
Hi Julian :wave: :) 

Are you sure your token has permissions to list on root level?

KV2 should be fully supported and is tested. Here a list of all commands that are tested against KV1 and KV2 https://github.com/fishi0x01/vsh/tree/master/test/suites/commands

**Comment by fishi0x01** [comment]
I just tried locally and cannot reproduce the issue.

What I did:

`docker-compose.yml`
```
---
version: "3.9"
services:
  vault:
    container_name: vault
    image: "vault:1.5.4"
    environment:
      - VAULT_ADDR=http://127.0.0.1:8200
      - VAULT_TOKEN=root
      - VAULT_DEV_ROOT_TOKEN_ID=root
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
    ports:
      - 8200:8200
```

```
docker exec vault /bin/sh -c vault secrets enable -version=2 -path=my-kv2 kv
```

```
$ VAULT_ADDR=http://localhost:8200 VAULT_TOKEN=root vsh
http://localhost:8200 /> ls
my-kv2/
http://localhost:8200 />
```
